nidq-master/config/routes.rb
NIDQueue::Application.routes.draw do
  resources :designs do
    member do
      get 'assist'
    end
    collection do
      get 'todays_queue'
    end
  end
  

  

end

nidq-master/app/models/design.rb
class Design < ActiveRecord::Base
end

nidq-master/app/controllers/application_controller.rb
require "urbanairship"

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  Urbanairship.application_key = 'HHyASKcvQfeZslB_KDSRdg'
  Urbanairship.application_secret = 'M9H-DwexRD6e1We2Aoa-Og'
  Urbanairship.master_secret = 'TepIM_3_QB2dcV9d7WRIFQ'
  Urbanairship.logger = Rails.logger
  Urbanairship.request_timeout = 5 # default
  
end

nidq-master/app/controllers/designs_controller.rb
require "urbanairship"

class DesignsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  
  respond_to :html, :json, :xml

  ##############################################
  # Boilerplate methods
  ##############################################

  #----------------------------------
  def index
    @designs = Design.all
    respond_with @Designs
  end

  #----------------------------------
  def show
    @design = Design.find(params[:id])
    respond_with @design
  end

  #----------------------------------
  def new
    @design = Design.new
  end

  #----------------------------------
  def edit
    @design = Design.find(params[:id])
  end

  #----------------------------------
  def create
    @design = Design.new(design_params)
    populateDesignWithDefaults()
    @design.save
    
    # send a notification through Urban Airship
    sendPushNotification()
    
    # Web server response
    respond_with @design
  end

  #----------------------------------
  def update
    @design = Design.find(params[:id])
    @design.update_attributes([params:design])
    respond_with @design
  end

  #----------------------------------
  def destroy
    @design = Design.find(params[:id])
    @design.destroy
    respond_with @design
  end
  
  ##############################################
  # Custom methods
  ##############################################
  def populateDesignWithDefaults
    # designId increases sequentially, starting at 1 if there are no designs in the queue
    @design.designId = Design.all.maximum(:designId) ? Design.all.maximum(:designId)+1 : 1
    
    # design is always in Open state initially
    @design.status = :Open
    
    # generate a random metricId between 284810601 and 284810699 (excluding multiples of 10 since these don't appear to have images)
    metricIdRandom = rand 100;
    while metricIdRandom % 10 == 0 do
      metricIdRandom = rand 100;
    end
    if (metricIdRandom < 10) then 
      @design.metricId = "28481060"+metricIdRandom.to_s 
    else 
      @design.metricId = "2848106"+metricIdRandom.to_s
    end
    
    @design.timestamp = Time.now.utc
  end    
  
  def sendPushNotification
    notification = {
      :audience => { :tag => ["Golf"] },
      :device_types => [ "ios" ],
      :notification => {:alert => "New design #{ @design.productName} for consumer #{ @design.consumerName }", 
      :ios => { :extra => { :terminal => "1", :name => @design.consumerName, :designId => @design.metricId } }}
    }
    Urbanairship.push(notification)
  end
  
  def todays_queue
    @designs = Design.where(created_at: Time.now.midnight..Time.now)
    respond_with @designs
  end
  
  def assist
    @design = Design.find(params[:id])
    if @design then
      @design.status = "Assisted"
      @design.save
    end
    respond_with @design
  end

  ##############################################
  # Private methods
  ##############################################
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_design
      @design = Design.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def design_params
      params.require(:design).permit(:designId, :metricId, :productName, :consumerName, :timestamp, :status)
    end
end

nidq-master/app/helpers/application_helper.rb
module ApplicationHelper
end

nidq-master/app/helpers/designs_helper.rb
module DesignsHelper
end

nidq-master/app/views/designs/_form.html.erb
<%= form_for(@design) do |f| %>
  <% if @design.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@design.errors.count, "error") %> prohibited this design from being saved:</h2>

      <ul>
      <% @design.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Product %><br>
    <%= f.text_field :productName %>
  </div>
  <div class="field">
    <%= f.label :Consumer %><br>
    <%= f.text_field :consumerName %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

nidq-master/app/views/designs/edit.html.erb
<h1>Editing design</h1>

<%= render 'form' %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

nidq-master/app/views/designs/index.html.erb
<h1>Listing designs</h1>

<table>
  <thead>
    <tr>
      <th>Design Id</th>
      <th>Metric Id</th>
      <th>Product Name</th>
      <th>Consumer Name</th>
      <th>Timestamp</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @designs.each do |design| %>
      <tr>
        <td><%= design.designId %></td>
        <td><%= design.metricId %></td>
        <td><%= design.productName %></td>
        <td><%= design.consumerName %></td>
        <td><%= design.timestamp %></td>
        <td><%= design.status %></td>
        <td><%= link_to 'Show', design %></td>
        <td><%= link_to 'Edit', edit_design_path(design) %></td>
        <td><%= link_to 'Destroy', design, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Design', new_design_path %>

nidq-master/app/views/designs/new.html.erb
<h1>New design</h1>

<%= render 'form' %>

<%= link_to 'Back', designs_path %>

nidq-master/app/views/designs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Designid:</strong>
  <%= @design.designId %>
</p>

<p>
  <strong>Metricid:</strong>
  <%= @design.metricId %>
</p>

<p>
  <strong>Productname:</strong>
  <%= @design.productName %>
</p>

<p>
  <strong>Consumername:</strong>
  <%= @design.consumerName %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @design.timestamp %>
</p>

<p>
  <strong>Status:</strong>
  <%= @design.status %>
</p>

<%= link_to 'Edit', edit_design_path(@design) %> |
<%= link_to 'Back', designs_path %>

nidq-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NIDQueue</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>